plugin: aws_ec2
regions:
  - ap-northeast-1

filters:
  instance-state-name: running
include_filters:
  - tag:Application:
    - 'go-grpc-sample'
  - tag:Stage:
    - 'production'

keyed_groups:
  - key: tags.ApplicationGroup
    prefix: ""
    separator: ""

hostnames:
  - tag:Name
  - ip-address
  - private-ip-address

compose:
  ansible_host: public_ip_address
